### ISSUE TITLE
Can't be opened in Logic 

### ISSUE THREAD

**Issue by Molnfront** [StrangeLoopsAudio/gRainbow#73]
validating Audio Unit gRainbow by StrangeLoops:

    AU Validation Tool
    Version: 1.10.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'SL01' - 'SLoo'
--------------------------------------------------
Manufacturer String: StrangeLoops
AudioUnit Name: gRainbow
Component Version: 0.2.2 (0x202)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF

validation result: couldn’t be opened

**Comment by bboettcher3** [comment]
Hi @Molnfront , I see that you're still using version 0.2.2! The newest versoin is 0.4.0, which has fixed this issue and has a lot of improvements :) you can grab it here: https://github.com/StrangeLoopsAudio/gRainbow/releases/latest
