### ISSUE TITLE
Patch Settings reset when "Set Selection" is hit

### ISSUE THREAD

**Issue by Thysbe** [StrangeLoopsAudio/gRainbow#79]
Steps to Recreate:

1. Load a file into Grainbow
2. Change patch settings (I tested grain & amp envelope settings, possibly more/all effected)
3. Load in a new audio file using the folder icon (testing with .wav)
4. Click the "Set Selection" button in the audio editor
5. Patch settings are reset to default

**Comment by bboettcher3** [comment]
Pushed a commit to feat/wip_redesign that fixes this which will be merged into main soon, will close then.

**Comment by bboettcher3** [comment]
Merged into main and creating the release in a few minutes, closing!
