### ISSUE TITLE
Patch settings are reset when closing/opening ableton

### ISSUE THREAD

**Issue by Thysbe** [StrangeLoopsAudio/gRainbow#80]
Steps to Recreate:

Open gRainbow in Ableton Live
Load a file into gRainbow
Change patch settings (I tested grain & amp envelope settings, possibly more/all effected)
Save the ableton project, close and re-open the project
Patch settings are reset to default

**Comment by bboettcher3** [comment]
Commit to fix this: eaaf876 on feat/wip_redesign, will be merged into main soon.

**Comment by bboettcher3** [comment]
Merged into main and creating the release in a few minutes, closing!
